import { Survey } from "@/hooks/useForetell";

export const dummySurveys: Survey[] = [
  {
    surveyId: "survey_ai_2025",
    title: "What is your sentiment about AI in 2025?",
    description: "Share your thoughts on the impact of AI this year.",
    createdBy: "user_abc",
    createdAt: new Date().toISOString(),
    expiry: "2025-06-12T23:59:59Z",
    maxResponses: 100,
    responses: [
      {
        uid: "user1",
        polarity: 1,
        score: 0.85,
        intensity: 0.9,
        answer: "AI is making life easier!",
      },
      {
        uid: "user2",
        polarity: -1,
        score: 0.1,
        intensity: 0.8,
        answer: "I'm worried about job loss.",
      },
      {
        uid: "user3",
        polarity: 0,
        score: 0.5,
        intensity: 1.0,
        answer: "It's a mixed bag.",
      },
      {
        uid: "user4",
        polarity: 1,
        score: 0.78,
        intensity: 0.7,
        answer: "AI has huge potential in healthcare.",
      },
      {
        uid: "user5",
        polarity: -1,
        score: 0.2,
        intensity: 0.6,
        answer: "AI could lead to privacy issues.",
      },
      {
        uid: "user6",
        polarity: 1,
        score: 0.9,
        intensity: 0.95,
        answer: "I love how AI powers smart assistants.",
      },
      {
        uid: "user7",
        polarity: 0,
        score: 0.45,
        intensity: 0.5,
        answer: "I'm still learning about AI.",
      },
      {
        uid: "user8",
        polarity: -1,
        score: 0.15,
        intensity: 0.9,
        answer: "AI might be biased and unfair.",
      },
      {
        uid: "user9",
        polarity: 1,
        score: 0.8,
        intensity: 0.85,
        answer: "AI art is fascinating and innovative.",
      },
      {
        uid: "user10",
        polarity: 0,
        score: 0.5,
        intensity: 0.7,
        answer: "I see both pros and cons.",
      },
    ],
  },
  {
    surveyId: "survey_climate_action",
    title: "How do you feel about current climate change efforts?",
    description: "Tell us your opinion on global climate action.",
    createdBy: "user_xyz",
    createdAt: new Date().toISOString(),
    expiry: "2025-06-30T23:59:59Z",
    maxResponses: 150,
    responses: [
      {
        uid: "user1",
        polarity: 1,
        score: 0.8,
        intensity: 0.7,
        answer: "It's encouraging to see renewable adoption.",
      },
      {
        uid: "user2",
        polarity: -1,
        score: 0.2,
        intensity: 0.8,
        answer: "Progress is too slow.",
      },
      {
        uid: "user3",
        polarity: 0,
        score: 0.5,
        intensity: 0.6,
        answer: "Some progress, but not enough.",
      },
      {
        uid: "user4",
        polarity: 1,
        score: 0.9,
        intensity: 0.95,
        answer: "Innovations in clean energy give me hope.",
      },
      {
        uid: "user5",
        polarity: -1,
        score: 0.1,
        intensity: 0.9,
        answer: "I distrust corporate greenwashing.",
      },
      {
        uid: "user6",
        polarity: 1,
        score: 0.75,
        intensity: 0.8,
        answer: "Youth movements are powerful.",
      },
      {
        uid: "user7",
        polarity: 0,
        score: 0.5,
        intensity: 0.4,
        answer: "I’m learning more but undecided.",
      },
      {
        uid: "user8",
        polarity: -1,
        score: 0.3,
        intensity: 0.7,
        answer: "Governments aren't doing enough.",
      },
      {
        uid: "user9",
        polarity: 1,
        score: 0.85,
        intensity: 0.9,
        answer: "Community projects inspire me.",
      },
      {
        uid: "user10",
        polarity: 0,
        score: 0.6,
        intensity: 0.5,
        answer: "Need more data to form an opinion.",
      },
    ],
  },
  {
    surveyId: "survey_weekend_fun",
    title: "What’s your favorite way to spend a weekend?",
    description: "Share your go-to weekend activities.",
    createdBy: "surveyCreator1",
    createdAt: new Date().toISOString(),
    expiry: "2025-05-15T23:59:59Z",
    maxResponses: 200,
    responses: [
      {
        uid: "user1",
        polarity: 1,
        score: 0.7,
        intensity: 0.6,
        answer: "I love hiking in the mountains.",
      },
      {
        uid: "user2",
        polarity: 1,
        score: 0.8,
        intensity: 0.7,
        answer: "Catching up on reading is my favorite.",
      },
      {
        uid: "user3",
        polarity: 1,
        score: 0.9,
        intensity: 0.9,
        answer: "Brunch with friends is the best.",
      },
      {
        uid: "user4",
        polarity: 1,
        score: 0.85,
        intensity: 0.8,
        answer: "Watching movies at home.",
      },
      {
        uid: "user5",
        polarity: -1,
        score: 0.2,
        intensity: 0.6,
        answer: "Weekends feel too short.",
      },
      {
        uid: "user6",
        polarity: 0,
        score: 0.5,
        intensity: 0.5,
        answer: "Depends on the weather.",
      },
      {
        uid: "user7",
        polarity: 1,
        score: 0.75,
        intensity: 0.7,
        answer: "Visiting local markets.",
      },
      {
        uid: "user8",
        polarity: -1,
        score: 0.3,
        intensity: 0.4,
        answer: "I have too much work to relax.",
      },
      {
        uid: "user9",
        polarity: 1,
        score: 0.8,
        intensity: 0.9,
        answer: "Playing video games.",
      },
      {
        uid: "user10",
        polarity: 1,
        score: 0.65,
        intensity: 0.6,
        answer: "Cooking new recipes.",
      },
    ],
  },
  {
    surveyId: "survey_remote_work",
    title: "How satisfied are you with remote work?",
    description: "Let us know your experience working remotely.",
    createdBy: "hr_team",
    createdAt: new Date().toISOString(),
    expiry: "2025-08-31T23:59:59Z",
    maxResponses: 120,
    responses: [
      {
        uid: "user1",
        polarity: 1,
        score: 0.9,
        intensity: 0.9,
        answer: "I love the flexibility.",
      },
      {
        uid: "user2",
        polarity: -1,
        score: 0.2,
        intensity: 0.8,
        answer: "I miss office camaraderie.",
      },
      {
        uid: "user3",
        polarity: 0,
        score: 0.5,
        intensity: 0.6,
        answer: "It's okay, but sometimes lonely.",
      },
      {
        uid: "user4",
        polarity: 1,
        score: 0.85,
        intensity: 0.7,
        answer: "Remote work has increased my productivity.",
      },
      {
        uid: "user5",
        polarity: -1,
        score: 0.15,
        intensity: 0.9,
        answer: "I struggle with work-life balance.",
      },
      {
        uid: "user6",
        polarity: 1,
        score: 0.8,
        intensity: 0.8,
        answer: "No commute is a huge plus.",
      },
      {
        uid: "user7",
        polarity: 0,
        score: 0.45,
        intensity: 0.5,
        answer: "Neutral—works sometimes, not others.",
      },
      {
        uid: "user8",
        polarity: -1,
        score: 0.3,
        intensity: 0.7,
        answer: "Zoom fatigue is real.",
      },
      {
        uid: "user9",
        polarity: 1,
        score: 0.7,
        intensity: 0.6,
        answer: "I can focus better at home.",
      },
      {
        uid: "user10",
        polarity: 1,
        score: 0.65,
        intensity: 0.5,
        answer: "I appreciate the cost savings.",
      },
    ],
  },
  {
    surveyId: "survey_healthy_eating",
    title: "What are your thoughts on healthy eating habits?",
    description: "Share your perspective on nutrition and diet.",
    createdBy: "nutritionist",
    createdAt: new Date().toISOString(),
    expiry: "2025-09-30T23:59:59Z",
    maxResponses: 180,
    responses: [
      {
        uid: "user1",
        polarity: 1,
        score: 0.8,
        intensity: 0.7,
        answer: "Balanced meals improved my energy.",
      },
      {
        uid: "user2",
        polarity: -1,
        score: 0.2,
        intensity: 0.6,
        answer: "Healthy options can be expensive.",
      },
      {
        uid: "user3",
        polarity: 0,
        score: 0.5,
        intensity: 0.5,
        answer: "I'm trying but it's a challenge.",
      },
      {
        uid: "user4",
        polarity: 1,
        score: 0.9,
        intensity: 0.8,
        answer: "I love experimenting with salads.",
      },
      {
        uid: "user5",
        polarity: -1,
        score: 0.1,
        intensity: 0.7,
        answer: "I miss comfort foods.",
      },
      {
        uid: "user6",
        polarity: 1,
        score: 0.75,
        intensity: 0.6,
        answer: "Meal prepping has helped me.",
      },
      {
        uid: "user7",
        polarity: 0,
        score: 0.5,
        intensity: 0.4,
        answer: "I'm flexible with my diet.",
      },
      {
        uid: "user8",
        polarity: -1,
        score: 0.3,
        intensity: 0.7,
        answer: "Nutrition myths are confusing.",
      },
      {
        uid: "user9",
        polarity: 1,
        score: 0.85,
        intensity: 0.9,
        answer: "Whole foods make me feel great.",
      },
      {
        uid: "user10",
        polarity: 0,
        score: 0.6,
        intensity: 0.5,
        answer: "I need more guidance.",
      },
    ],
  },
];
